# -*- coding: utf-8 -*-
"""Technology / electronics property families."""
from lib_core import *

FAM = {}

# ------------------------------------------------------------------ mobile phone
FAM['mobile_phone'] = blk(IDENT, [
    D('main', 'Model Year', 'سنة الإصدار',
      '2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026', required='Yes'),
    D('general', 'Operating System', 'نظام التشغيل',
      'Android, iOS, HarmonyOS, KaiOS, Feature Phone OS', required='Yes'),
    T('general', 'OS Version', 'إصدار نظام التشغيل'),
    D('spec', 'Phone Type', 'نوع الهاتف',
      'Smartphone, Feature Phone, Foldable (Book Style), Foldable (Flip Style), '
      'Rugged Phone, Gaming Phone', required='Yes'),
    # display
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      'Below 5.5 inch, 5.5-6.0 inch, 6.1-6.5 inch, 6.6-6.9 inch, 7.0 inch and above',
      required='Yes'),
    D('display', 'Display Technology', 'تقنية الشاشة',
      'IPS LCD, TFT LCD, PLS LCD, OLED, AMOLED, Super AMOLED, Dynamic AMOLED, '
      'LTPO AMOLED, Super Retina XDR, Fluid AMOLED'),
    D('display', 'Screen Resolution', 'دقة الشاشة',
      'HD+ (720p), Full HD+ (1080p), Quad HD+ (1440p), 4K'),
    D('display', 'Refresh Rate (Hz)', 'معدل التحديث (هرتز)',
      '60 Hz, 90 Hz, 120 Hz, 144 Hz, 165 Hz, Adaptive 1-120 Hz'),
    I('display', 'Peak Brightness (nits)', 'أقصى سطوع (نِت)',
      'Under 600 nits, 600-1000 nits, 1001-1500 nits, 1501-2000 nits, Above 2000 nits'),
    D('display', 'Screen Protection', 'حماية الشاشة',
      'Corning Gorilla Glass, Gorilla Glass Victus, Gorilla Glass Victus 2, '
      'Ceramic Shield, Panda Glass, Dragontrail, None'),
    D('display', 'Display Notch / Cutout', 'شكل قصّة الشاشة',
      'Punch Hole, Notch, Dynamic Island, Full Screen, Waterdrop, Under-Display Camera'),
    # performance
    D('perf', 'Chipset / Processor', 'المعالج / الشريحة',
      'Apple A-Series, Apple Bionic, Qualcomm Snapdragon 8 Series, '
      'Qualcomm Snapdragon 7 Series, Qualcomm Snapdragon 6 Series, '
      'Qualcomm Snapdragon 4 Series, MediaTek Dimensity, MediaTek Helio, '
      'Samsung Exynos, Google Tensor, Unisoc, Kirin, Other', required='Yes'),
    T('perf', 'Processor Model', 'موديل المعالج'),
    D('perf', 'CPU Cores', 'عدد أنوية المعالج',
      'Quad-Core, Hexa-Core, Octa-Core, Deca-Core'),
    D('perf', 'Fabrication Process', 'دقة التصنيع',
      '3 nm, 4 nm, 5 nm, 6 nm, 7 nm, 8 nm, 10 nm, 12 nm, 14 nm'),
    T('perf', 'GPU', 'معالج الرسوميات'),
    # memory
    D('mem', 'RAM', 'الذاكرة العشوائية',
      '2 GB, 3 GB, 4 GB, 6 GB, 8 GB, 12 GB, 16 GB, 18 GB, 24 GB',
      required='Yes', option='Yes'),
    D('storage', 'Internal Storage', 'التخزين الداخلي',
      '32 GB, 64 GB, 128 GB, 256 GB, 512 GB, 1 TB',
      required='Yes', option='Yes'),
    D('storage', 'Storage Type', 'نوع التخزين',
      'eMMC 5.1, UFS 2.1, UFS 2.2, UFS 3.1, UFS 4.0, UFS 4.1, NVMe'),
    B('storage', 'Expandable Storage (microSD)', 'تخزين قابل للتوسعة (microSD)'),
    # camera
    D('cam', 'Main Camera (MP)', 'الكاميرا الرئيسية (ميجابكسل)',
      'Below 12 MP, 12 MP, 13 MP, 48 MP, 50 MP, 64 MP, 108 MP, 200 MP', required='Yes'),
    D('cam', 'Rear Camera Setup', 'ترتيب الكاميرا الخلفية',
      'Single Camera, Dual Camera, Triple Camera, Quad Camera'),
    D('cam', 'Ultra-Wide Camera (MP)', 'الكاميرا فائقة الاتساع (ميجابكسل)',
      'Not Available, 8 MP, 12 MP, 13 MP, 16 MP, 48 MP, 50 MP'),
    D('cam', 'Telephoto / Zoom Camera', 'كاميرا التقريب (تليفوتو)',
      'Not Available, 2x Optical, 3x Optical, 5x Optical, 10x Optical, Periscope Zoom'),
    D('cam', 'Front Camera (MP)', 'الكاميرا الأمامية (ميجابكسل)',
      '5 MP, 8 MP, 10 MP, 12 MP, 16 MP, 20 MP, 32 MP, 40 MP, 50 MP', required='Yes'),
    D('cam', 'Video Recording', 'تسجيل الفيديو',
      '1080p @30fps, 1080p @60fps, 4K @30fps, 4K @60fps, 8K @24fps, 8K @30fps'),
    B('cam', 'Optical Image Stabilisation (OIS)', 'مثبّت الصورة البصري (OIS)'),
    D('cam', 'Flash Type', 'نوع الفلاش',
      'Single LED, Dual LED, Dual-Tone LED, Quad LED, Ring Flash, No Flash'),
    # battery
    D('batt', 'Battery Capacity (mAh)', 'سعة البطارية (مللي أمبير/ساعة)',
      'Below 3000 mAh, 3000-4000 mAh, 4001-5000 mAh, 5001-6000 mAh, Above 6000 mAh',
      required='Yes'),
    D('batt', 'Wired Charging Speed (W)', 'سرعة الشحن السلكي (واط)',
      '10 W, 15 W, 18 W, 20 W, 25 W, 33 W, 45 W, 65 W, 80 W, 100 W, 120 W, 150 W, 240 W'),
    D('batt', 'Wireless Charging', 'الشحن اللاسلكي',
      'Not Supported, Qi Wireless, MagSafe, 15 W Wireless, 50 W Wireless'),
    B('batt', 'Reverse Charging', 'الشحن العكسي'),
    D('batt', 'Battery Type', 'نوع البطارية',
      'Li-Ion, Li-Polymer, Silicon-Carbon'),
    # connectivity
    D('conn', 'Network', 'الشبكة', '2G, 3G, 4G LTE, 5G', required='Yes'),
    D('conn', 'SIM Type', 'نوع الشريحة',
      'Single SIM, Dual SIM (Nano), Dual SIM (Nano + eSIM), eSIM Only, Triple Slot'),
    D('conn', 'Wi-Fi', 'الواي فاي',
      'Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax), Wi-Fi 6E, Wi-Fi 7'),
    D('conn', 'Bluetooth Version', 'إصدار البلوتوث',
      'Bluetooth 4.2, Bluetooth 5.0, Bluetooth 5.1, Bluetooth 5.2, Bluetooth 5.3, Bluetooth 5.4, Bluetooth 6.0'),
    D('conn', 'Charging Port', 'منفذ الشحن',
      'USB Type-C, Lightning, Micro USB, USB Type-C (Thunderbolt)'),
    B('conn', 'NFC', 'تقنية NFC'),
    B('conn', 'Infrared (IR Blaster)', 'منفذ الأشعة تحت الحمراء'),
    B('conn', '3.5mm Headphone Jack', 'منفذ سماعات 3.5 ملم'),
    D('conn', 'Satellite Connectivity', 'الاتصال عبر الأقمار الصناعية',
      'Not Supported, Emergency SOS via Satellite, Satellite Messaging'),
    # sensors & security
    D('sensors', 'Fingerprint Sensor', 'مستشعر البصمة',
      'Under-Display (Optical), Under-Display (Ultrasonic), Side-Mounted, '
      'Rear-Mounted, Not Available'),
    D('sensors', 'Face Unlock', 'فتح بالتعرف على الوجه',
      '2D Face Unlock, 3D Face ID, Not Available'),
    T('sensors', 'Sensors', 'المستشعرات'),
    # body
    D('design', 'Body Material', 'خامة الهيكل',
      'Plastic / Polycarbonate, Aluminium Frame + Glass, Titanium Frame + Glass, '
      'Stainless Steel + Glass, Aramid Fibre, Eco Leather, Full Glass'),
    D('safety', 'Water & Dust Resistance', 'مقاومة الماء والغبار', IP_RATING),
    N('design', 'Thickness (mm)', 'السماكة (ملم)',
      'Under 7 mm, 7-8 mm, 8-9 mm, 9-10 mm, Above 10 mm'),
    N('design', 'Weight (g)', 'الوزن (جم)',
      'Under 150 g, 150-180 g, 181-200 g, 201-230 g, Above 230 g'),
    D('audio', 'Speakers', 'السماعات', 'Mono Speaker, Stereo Speakers, Dual Stereo Speakers'),
    B('audio', 'Dolby Atmos', 'دولبي أتموس'),
    B('feat', 'Stylus Support', 'دعم القلم الرقمي'),
], COLOR, ELEC_COMMERCE)

# ------------------------------------------------------------------ tablet
FAM['tablet'] = blk(IDENT, [
    D('main', 'Model Year', 'سنة الإصدار',
      '2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026'),
    D('general', 'Operating System', 'نظام التشغيل',
      'iPadOS, Android, HarmonyOS, Windows, Fire OS', required='Yes'),
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      'Below 8 inch, 8-9.9 inch, 10-10.9 inch, 11-12.9 inch, 13 inch and above',
      required='Yes'),
    D('display', 'Display Technology', 'تقنية الشاشة',
      'IPS LCD, TFT LCD, OLED, AMOLED, Liquid Retina, Mini-LED, Tandem OLED'),
    D('display', 'Screen Resolution', 'دقة الشاشة',
      'HD, Full HD, 2K, 2.5K, Retina, 4K'),
    D('display', 'Refresh Rate (Hz)', 'معدل التحديث (هرتز)',
      '60 Hz, 90 Hz, 120 Hz, Adaptive 10-120 Hz'),
    D('perf', 'Chipset / Processor', 'المعالج / الشريحة',
      'Apple M-Series, Apple A-Series, Qualcomm Snapdragon, MediaTek Dimensity, '
      'MediaTek Helio, Samsung Exynos, Unisoc, Intel, Other', required='Yes'),
    D('perf', 'CPU Cores', 'عدد أنوية المعالج', 'Quad-Core, Hexa-Core, Octa-Core, Deca-Core'),
    D('mem', 'RAM', 'الذاكرة العشوائية',
      '2 GB, 3 GB, 4 GB, 6 GB, 8 GB, 12 GB, 16 GB', required='Yes', option='Yes'),
    D('storage', 'Internal Storage', 'التخزين الداخلي',
      '32 GB, 64 GB, 128 GB, 256 GB, 512 GB, 1 TB, 2 TB', required='Yes', option='Yes'),
    B('storage', 'Expandable Storage (microSD)', 'تخزين قابل للتوسعة (microSD)'),
    D('conn', 'Connectivity', 'الاتصال',
      'Wi-Fi Only, Wi-Fi + Cellular (4G), Wi-Fi + Cellular (5G)', required='Yes', option='Yes'),
    D('conn', 'Wi-Fi', 'الواي فاي',
      'Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax), Wi-Fi 6E, Wi-Fi 7'),
    D('conn', 'Bluetooth Version', 'إصدار البلوتوث',
      'Bluetooth 4.2, Bluetooth 5.0, Bluetooth 5.1, Bluetooth 5.2, Bluetooth 5.3, Bluetooth 5.4'),
    D('conn', 'Charging Port', 'منفذ الشحن', 'USB Type-C, Lightning, Micro USB'),
    D('cam', 'Rear Camera (MP)', 'الكاميرا الخلفية (ميجابكسل)',
      'Not Available, 5 MP, 8 MP, 12 MP, 13 MP, 48 MP'),
    D('cam', 'Front Camera (MP)', 'الكاميرا الأمامية (ميجابكسل)',
      '2 MP, 5 MP, 8 MP, 12 MP, 13 MP'),
    D('batt', 'Battery Capacity (mAh)', 'سعة البطارية (مللي أمبير/ساعة)',
      'Below 5000 mAh, 5000-7000 mAh, 7001-9000 mAh, 9001-11000 mAh, Above 11000 mAh'),
    D('batt', 'Charging Speed (W)', 'سرعة الشحن (واط)',
      '10 W, 15 W, 18 W, 20 W, 25 W, 30 W, 45 W, 65 W'),
    B('feat', 'Stylus / Pen Support', 'دعم القلم الرقمي'),
    B('feat', 'Keyboard Support', 'دعم لوحة المفاتيح'),
    D('sensors', 'Biometric Unlock', 'الفتح البيومتري',
      'Fingerprint (Power Button), Fingerprint (Under-Display), Face Unlock, Face ID, Not Available'),
    D('audio', 'Speakers', 'السماعات', 'Dual Speakers, Quad Speakers, Stereo Speakers'),
    B('conn', '3.5mm Headphone Jack', 'منفذ سماعات 3.5 ملم'),
    N('design', 'Weight (g)', 'الوزن (جم)',
      'Under 300 g, 300-450 g, 451-600 g, 601-800 g, Above 800 g'),
    D('design', 'Body Material', 'خامة الهيكل', 'Aluminium, Plastic, Glass, Magnesium Alloy'),
    D('usage', 'Recommended Use', 'الاستخدام الموصى به',
      'Everyday Use, Study & Education, Business & Productivity, Drawing & Design, '
      'Gaming, Kids, Media & Entertainment'),
], COLOR, ELEC_COMMERCE)

# ------------------------------------------------------------------ laptop
FAM['laptop'] = blk(IDENT, [
    D('spec', 'Laptop Type', 'نوع الحاسوب المحمول',
      'Everyday / Home, Business, Gaming, Ultrabook / Thin & Light, 2-in-1 Convertible, '
      'Workstation, Chromebook, Netbook', required='Yes'),
    D('perf', 'Processor (CPU)', 'المعالج',
      'Intel Core i3, Intel Core i5, Intel Core i7, Intel Core i9, Intel Core Ultra 5, '
      'Intel Core Ultra 7, Intel Core Ultra 9, Intel Celeron, Intel Pentium, '
      'AMD Ryzen 3, AMD Ryzen 5, AMD Ryzen 7, AMD Ryzen 9, AMD Athlon, '
      'Apple M1, Apple M2, Apple M3, Apple M4, Qualcomm Snapdragon X, Other',
      required='Yes'),
    T('perf', 'Processor Model', 'موديل المعالج'),
    D('perf', 'Processor Generation', 'جيل المعالج',
      '8th Gen, 9th Gen, 10th Gen, 11th Gen, 12th Gen, 13th Gen, 14th Gen, '
      'Series 1 / Ultra, Ryzen 5000, Ryzen 6000, Ryzen 7000, Ryzen 8000, Ryzen AI 300, Not Applicable'),
    I('perf', 'Number of Cores', 'عدد الأنوية', '2, 4, 6, 8, 10, 12, 14, 16, 20, 24'),
    D('perf', 'Graphics Card (GPU)', 'كرت الشاشة',
      'Integrated Graphics, Intel Iris Xe, Intel Arc, NVIDIA GeForce RTX 50 Series, '
      'NVIDIA GeForce RTX 40 Series, NVIDIA GeForce RTX 30 Series, NVIDIA GeForce GTX, '
      'NVIDIA Quadro / RTX Pro, AMD Radeon, Apple GPU, Other', required='Yes'),
    D('perf', 'Graphics Memory (VRAM)', 'ذاكرة كرت الشاشة',
      'Shared, 2 GB, 4 GB, 6 GB, 8 GB, 12 GB, 16 GB, 24 GB'),
    D('mem', 'RAM (GB)', 'الذاكرة العشوائية (جيجابايت)',
      '4 GB, 8 GB, 16 GB, 24 GB, 32 GB, 48 GB, 64 GB, 128 GB', required='Yes', option='Yes'),
    D('mem', 'RAM Type', 'نوع الذاكرة',
      'DDR4, DDR5, LPDDR4X, LPDDR5, LPDDR5X, Unified Memory'),
    B('mem', 'RAM Upgradeable', 'الذاكرة قابلة للترقية'),
    D('storage', 'Storage Capacity', 'سعة التخزين',
      '128 GB, 256 GB, 512 GB, 1 TB, 2 TB, 4 TB', required='Yes', option='Yes'),
    D('storage', 'Storage Type', 'نوع التخزين',
      'SSD (SATA), SSD (NVMe PCIe 3.0), SSD (NVMe PCIe 4.0), SSD (NVMe PCIe 5.0), '
      'HDD, SSD + HDD, eMMC'),
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      '11.6 inch, 12.4 inch, 13.3 inch, 13.6 inch, 14 inch, 15.6 inch, 16 inch, '
      '17.3 inch, 18 inch', required='Yes'),
    D('display', 'Screen Resolution', 'دقة الشاشة',
      'HD (1366x768), Full HD (1920x1080), WUXGA (1920x1200), 2K (2560x1440), '
      'WQXGA (2560x1600), 3K (2880x1800), 4K UHD (3840x2160), Retina'),
    D('display', 'Display Panel Type', 'نوع لوحة الشاشة',
      'TN, IPS, VA, OLED, Mini-LED, Liquid Retina, Retina XDR'),
    D('display', 'Refresh Rate (Hz)', 'معدل التحديث (هرتز)',
      '60 Hz, 90 Hz, 120 Hz, 144 Hz, 165 Hz, 240 Hz, 300 Hz, 360 Hz'),
    B('display', 'Touchscreen', 'شاشة لمس'),
    D('display', 'Screen Finish', 'نوع سطح الشاشة', 'Matte / Anti-Glare, Glossy'),
    D('general', 'Operating System', 'نظام التشغيل',
      'Windows 11 Home, Windows 11 Pro, Windows 10, macOS, Chrome OS, Linux, Free DOS / No OS',
      required='Yes'),
    D('conn', 'Ports', 'المنافذ',
      'USB-A, USB-C, Thunderbolt 4, Thunderbolt 5, HDMI, DisplayPort, '
      'Ethernet (RJ45), SD Card Reader, microSD Reader, 3.5mm Audio Jack, '
      'Barrel Charging Port, MagSafe'),
    I('conn', 'Number of USB Ports', 'عدد منافذ USB', '1, 2, 3, 4, 5, 6'),
    D('conn', 'Wi-Fi', 'الواي فاي',
      'Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax), Wi-Fi 6E, Wi-Fi 7'),
    D('conn', 'Bluetooth Version', 'إصدار البلوتوث',
      'Bluetooth 5.0, Bluetooth 5.1, Bluetooth 5.2, Bluetooth 5.3, Bluetooth 5.4'),
    D('batt', 'Battery Capacity (Wh)', 'سعة البطارية (واط/ساعة)',
      'Under 40 Wh, 40-50 Wh, 51-60 Wh, 61-75 Wh, 76-90 Wh, Above 90 Wh'),
    D('batt', 'Battery Life (hours)', 'عمر البطارية (ساعة)',
      'Up to 4 Hours, 5-8 Hours, 9-12 Hours, 13-18 Hours, Above 18 Hours'),
    D('batt', 'Charger Power (W)', 'قدرة الشاحن (واط)',
      '30 W, 45 W, 65 W, 90 W, 100 W, 120 W, 140 W, 180 W, 200 W, 240 W, 330 W'),
    D('feat', 'Keyboard Type', 'نوع لوحة المفاتيح',
      'Standard, Backlit, RGB Backlit, Mechanical, Numeric Keypad Included, Arabic / English'),
    D('feat', 'Webcam', 'الكاميرا',
      'HD 720p, Full HD 1080p, 2K, 5 MP, IR Camera (Windows Hello), No Webcam'),
    D('sensors', 'Biometric Security', 'الحماية البيومترية',
      'Fingerprint Reader, Face Recognition (IR), Touch ID, Both, Not Available'),
    D('audio', 'Audio System', 'نظام الصوت',
      'Stereo Speakers, Dolby Atmos, DTS Audio, Bang & Olufsen, Harman Kardon, Bose, JBL'),
    D('mat', 'Body Material', 'خامة الهيكل',
      'Plastic / Polycarbonate, Aluminium, Magnesium Alloy, Carbon Fibre, Metal & Plastic'),
    N('design', 'Weight (kg)', 'الوزن (كجم)',
      'Under 1 kg, 1 - 1.4 kg, 1.5 - 1.9 kg, 2 - 2.4 kg, 2.5 - 3 kg, Above 3 kg'),
    N('design', 'Thickness (mm)', 'السماكة (ملم)',
      'Under 15 mm, 15-18 mm, 19-22 mm, 23-27 mm, Above 27 mm'),
    B('feat', 'Fingerprint-Resistant Coating', 'طلاء مقاوم لبصمات الأصابع'),
    D('usage', 'Recommended Use', 'الاستخدام الموصى به',
      'Everyday Use, Study & Education, Business & Office, Gaming, '
      'Video Editing & 3D, Programming, Graphic Design, Travel'),
], COLOR, ELEC_COMMERCE)

# ------------------------------------------------------------------ desktop / AIO
FAM['desktop'] = blk(IDENT, [
    D('spec', 'Computer Type', 'نوع الحاسوب',
      'Desktop Tower, All-in-One, Mini PC, Gaming PC, Workstation, Barebone, Stick PC',
      required='Yes'),
    D('perf', 'Processor (CPU)', 'المعالج',
      'Intel Core i3, Intel Core i5, Intel Core i7, Intel Core i9, Intel Core Ultra 5, '
      'Intel Core Ultra 7, Intel Core Ultra 9, Intel Celeron, Intel Xeon, '
      'AMD Ryzen 3, AMD Ryzen 5, AMD Ryzen 7, AMD Ryzen 9, AMD Threadripper, '
      'Apple M-Series, Other', required='Yes'),
    T('perf', 'Processor Model', 'موديل المعالج'),
    D('perf', 'Graphics Card (GPU)', 'كرت الشاشة',
      'Integrated Graphics, NVIDIA GeForce RTX 50 Series, NVIDIA GeForce RTX 40 Series, '
      'NVIDIA GeForce RTX 30 Series, NVIDIA GeForce GTX, NVIDIA Quadro / RTX Pro, '
      'AMD Radeon RX, Intel Arc, Apple GPU, Other'),
    D('perf', 'Graphics Memory (VRAM)', 'ذاكرة كرت الشاشة',
      'Shared, 2 GB, 4 GB, 6 GB, 8 GB, 12 GB, 16 GB, 24 GB, 32 GB'),
    D('mem', 'RAM (GB)', 'الذاكرة العشوائية (جيجابايت)',
      '4 GB, 8 GB, 16 GB, 32 GB, 64 GB, 128 GB', required='Yes', option='Yes'),
    D('mem', 'RAM Type', 'نوع الذاكرة', 'DDR4, DDR5, LPDDR5, Unified Memory'),
    D('storage', 'Storage Capacity', 'سعة التخزين',
      '256 GB, 512 GB, 1 TB, 2 TB, 4 TB, 8 TB', required='Yes', option='Yes'),
    D('storage', 'Storage Type', 'نوع التخزين',
      'SSD (SATA), SSD (NVMe), HDD, SSD + HDD, Dual SSD'),
    D('general', 'Operating System', 'نظام التشغيل',
      'Windows 11 Home, Windows 11 Pro, Windows 10, macOS, Linux, Free DOS / No OS'),
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      'Not Applicable, 21.5 inch, 23.8 inch, 24 inch, 27 inch, 32 inch, 34 inch'),
    D('display', 'Screen Resolution', 'دقة الشاشة',
      'Not Applicable, Full HD (1920x1080), 2K (2560x1440), 4K UHD (3840x2160), 5K, Retina'),
    D('spec', 'Motherboard Form Factor', 'مقاس اللوحة الأم',
      'ATX, Micro-ATX, Mini-ITX, E-ATX, Proprietary, Not Applicable'),
    D('spec', 'Case Size', 'حجم الصندوق',
      'Full Tower, Mid Tower, Mini Tower, Small Form Factor (SFF), Ultra Small (USFF), Not Applicable'),
    D('power', 'Power Supply (W)', 'قدرة مزود الطاقة (واط)',
      '180 W, 250 W, 350 W, 450 W, 550 W, 650 W, 750 W, 850 W, 1000 W, 1200 W, 1600 W'),
    D('power', 'PSU Efficiency Rating', 'تصنيف كفاءة مزود الطاقة',
      '80 Plus, 80 Plus Bronze, 80 Plus Silver, 80 Plus Gold, 80 Plus Platinum, '
      '80 Plus Titanium, Not Rated'),
    D('spec', 'Cooling System', 'نظام التبريد',
      'Air Cooling, Liquid / AIO Cooling, Custom Water Cooling, Passive / Fanless'),
    D('conn', 'Ports', 'المنافذ',
      'USB-A, USB-C, Thunderbolt, HDMI, DisplayPort, VGA, DVI, Ethernet (RJ45), '
      'SD Card Reader, 3.5mm Audio Jack, PS/2'),
    D('conn', 'Wi-Fi', 'الواي فاي',
      'Not Available, Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax), Wi-Fi 6E, Wi-Fi 7'),
    D('conn', 'Ethernet Speed', 'سرعة الإيثرنت',
      'Not Available, 100 Mbps, 1 Gbps, 2.5 Gbps, 5 Gbps, 10 Gbps'),
    D('conn', 'Bluetooth Version', 'إصدار البلوتوث',
      'Not Available, Bluetooth 5.0, Bluetooth 5.1, Bluetooth 5.2, Bluetooth 5.3'),
    B('pack', 'Keyboard & Mouse Included', 'يشمل لوحة مفاتيح وفأرة'),
    D('usage', 'Recommended Use', 'الاستخدام الموصى به',
      'Home & Office, Business, Gaming, Content Creation, Engineering / CAD, '
      'Server & Virtualisation, Education'),
], COLOR, ELEC_COMMERCE)

# ------------------------------------------------------------------ monitor
FAM['monitor'] = blk(IDENT, [
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      '19 inch, 21.5 inch, 23.8 inch, 24 inch, 27 inch, 28 inch, 32 inch, 34 inch, '
      '38 inch, 42 inch, 49 inch', required='Yes', option='Yes'),
    D('display', 'Resolution', 'الدقة',
      'HD (1366x768), Full HD (1920x1080), 2K QHD (2560x1440), '
      'UWQHD (3440x1440), 4K UHD (3840x2160), 5K, 8K', required='Yes'),
    D('display', 'Panel Type', 'نوع اللوحة', 'TN, IPS, VA, OLED, QD-OLED, Nano IPS, Mini-LED'),
    D('display', 'Refresh Rate (Hz)', 'معدل التحديث (هرتز)',
      '60 Hz, 75 Hz, 100 Hz, 120 Hz, 144 Hz, 165 Hz, 180 Hz, 240 Hz, 360 Hz, 500 Hz'),
    D('display', 'Response Time', 'زمن الاستجابة',
      '0.03 ms, 0.5 ms, 1 ms, 2 ms, 4 ms, 5 ms, 8 ms'),
    D('display', 'Aspect Ratio', 'نسبة العرض إلى الارتفاع', '16:9, 16:10, 21:9, 32:9, 4:3'),
    D('display', 'Screen Curvature', 'انحناء الشاشة',
      'Flat, Curved 1000R, Curved 1500R, Curved 1800R, Curved 3000R'),
    I('display', 'Brightness (cd/m²)', 'السطوع (شمعة/م²)',
      '250 cd/m², 300 cd/m², 350 cd/m², 400 cd/m², 500 cd/m², 600 cd/m², 1000 cd/m²'),
    D('display', 'Contrast Ratio', 'نسبة التباين',
      '1000:1, 3000:1, 4000:1, 5000:1, 1,000,000:1, Infinite'),
    D('display', 'HDR Support', 'دعم HDR',
      'No HDR, HDR10, HDR10+, DisplayHDR 400, DisplayHDR 600, DisplayHDR 1000, Dolby Vision'),
    D('display', 'Colour Gamut', 'نطاق الألوان',
      'sRGB 99%, sRGB 100%, DCI-P3 90%, DCI-P3 95%, DCI-P3 98%, Adobe RGB 99%, NTSC 72%'),
    D('feat', 'Adaptive Sync', 'المزامنة التكيفية',
      'None, AMD FreeSync, AMD FreeSync Premium, AMD FreeSync Premium Pro, '
      'NVIDIA G-Sync, NVIDIA G-Sync Compatible'),
    D('conn', 'Video Inputs', 'مداخل الفيديو',
      'HDMI 1.4, HDMI 2.0, HDMI 2.1, DisplayPort 1.2, DisplayPort 1.4, '
      'DisplayPort 2.1, USB-C (DP Alt Mode), Thunderbolt, VGA, DVI'),
    I('conn', 'Number of HDMI Ports', 'عدد منافذ HDMI', '0, 1, 2, 3, 4'),
    B('conn', 'USB Hub Built-In', 'موزّع USB مدمج'),
    D('power', 'USB-C Power Delivery (W)', 'شحن USB-C (واط)',
      'Not Supported, 15 W, 45 W, 65 W, 90 W, 100 W, 140 W'),
    B('audio', 'Built-In Speakers', 'سماعات مدمجة'),
    D('design', 'Stand Adjustment', 'تعديل القاعدة',
      'Tilt Only, Tilt & Height, Tilt / Height / Swivel, Full Ergonomic (incl. Pivot), Fixed'),
    D('design', 'VESA Mount', 'حامل VESA',
      'Not Supported, 75x75 mm, 100x100 mm, 200x200 mm, 400x400 mm'),
    B('feat', 'Flicker-Free', 'خالٍ من الوميض'),
    B('feat', 'Blue Light Filter', 'مرشّح الضوء الأزرق'),
    B('feat', 'Built-In Webcam', 'كاميرا مدمجة'),
    D('usage', 'Recommended Use', 'الاستخدام الموصى به',
      'Office & Productivity, Gaming, Graphic Design & Photo Editing, Video Editing, '
      'Programming, Home & Entertainment'),
    D('env', 'Energy Efficiency Class', 'فئة كفاءة الطاقة', ENERGY),
], COLOR, ELEC_COMMERCE)

# ------------------------------------------------------------------ television
FAM['television'] = blk(IDENT, [
    D('display', 'Screen Size (inch)', 'حجم الشاشة (بوصة)',
      '24 inch, 32 inch, 40 inch, 43 inch, 50 inch, 55 inch, 65 inch, 75 inch, '
      '77 inch, 85 inch, 98 inch, 100 inch', required='Yes', option='Yes'),
    D('display', 'Resolution', 'الدقة', 'HD, Full HD, 4K UHD, 8K UHD', required='Yes'),
    D('display', 'Display Technology', 'تقنية الشاشة',
      'LED, LCD, QLED, OLED, QD-OLED, Mini-LED, Neo QLED, Nano Cell, Crystal UHD, ULED',
      required='Yes'),
    D('display', 'Refresh Rate (Hz)', 'معدل التحديث (هرتز)',
      '50 Hz, 60 Hz, 100 Hz, 120 Hz, 144 Hz, 165 Hz'),
    D('display', 'HDR Support', 'دعم HDR',
      'No HDR, HDR10, HDR10+, HLG, Dolby Vision, Dolby Vision IQ'),
    I('display', 'Peak Brightness (nits)', 'أقصى سطوع (نِت)',
      'Under 300 nits, 300-500 nits, 501-800 nits, 801-1500 nits, Above 1500 nits'),
    D('display', 'Screen Type', 'شكل الشاشة', 'Flat, Curved, Rotating / Portrait'),
    D('smart', 'Operating System', 'نظام التشغيل',
      'Android TV, Google TV, webOS, Tizen, Roku TV, Fire TV, VIDAA, '
      'My Home Screen, Non-Smart', required='Yes'),
    B('smart', 'Smart TV', 'تلفزيون ذكي'),
    D('smart', 'Voice Assistant', 'المساعد الصوتي',
      'Google Assistant, Amazon Alexa, Bixby, Apple Siri (AirPlay), Multiple, None'),
    B('smart', 'Screen Mirroring / Casting', 'مشاركة الشاشة'),
    D('smart', 'Streaming Apps', 'تطبيقات البث',
      'Netflix, YouTube, Shahid, StarzPlay, OSN+, Amazon Prime Video, Disney+, '
      'Apple TV+, Spotify, Multiple Apps'),
    I('conn', 'Number of HDMI Ports', 'عدد منافذ HDMI', '1, 2, 3, 4, 5'),
    D('conn', 'HDMI Version', 'إصدار HDMI', 'HDMI 1.4, HDMI 2.0, HDMI 2.1'),
    I('conn', 'Number of USB Ports', 'عدد منافذ USB', '0, 1, 2, 3, 4'),
    D('conn', 'Wi-Fi', 'الواي فاي',
      'Not Available, Wi-Fi 4, Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax)'),
    B('conn', 'Bluetooth', 'بلوتوث'),
    B('conn', 'Ethernet (LAN) Port', 'منفذ إيثرنت'),
    D('conn', 'Audio Output', 'مخرج الصوت',
      'Optical / Toslink, HDMI eARC, HDMI ARC, 3.5mm Jack, Coaxial, Bluetooth Audio'),
    D('audio', 'Sound Output (W)', 'قدرة الصوت (واط)',
      '10 W, 16 W, 20 W, 30 W, 40 W, 50 W, 60 W, 70 W, 80 W'),
    D('audio', 'Speaker Configuration', 'تكوين السماعات',
      '2.0 Channel, 2.1 Channel, 2.2 Channel, 4.2 Channel, 4.2.2 Channel, 6.2.2 Channel'),
    D('audio', 'Audio Technology', 'تقنية الصوت',
      'Dolby Atmos, Dolby Digital Plus, DTS Virtual:X, DTS:X, Object Tracking Sound, '
      'AI Sound, Standard Stereo'),
    D('feat', 'Gaming Features', 'ميزات الألعاب',
      'ALLM (Auto Low Latency Mode), VRR (Variable Refresh Rate), AMD FreeSync, '
      'NVIDIA G-Sync, Game Mode, Cloud Gaming, None'),
    D('feat', 'Tuner Type', 'نوع المستقبل',
      'DVB-T2, DVB-S2, DVB-C, DVB-T2/S2/C Combo, Analogue Only, No Tuner'),
    D('design', 'VESA Wall Mount', 'حامل الجدار VESA',
      '100x100 mm, 200x200 mm, 300x300 mm, 400x400 mm, 600x400 mm, 800x400 mm, Not Supported'),
    B('pack', 'Wall Mount Included', 'يشمل حامل جدار'),
    B('pack', 'Remote Control Included', 'يشمل جهاز تحكم'),
    D('feat', 'Remote Type', 'نوع جهاز التحكم',
      'Standard IR Remote, Bluetooth Smart Remote, Voice Remote, Solar Remote, Magic Remote'),
    D('env', 'Energy Efficiency Class', 'فئة كفاءة الطاقة', ENERGY),
    I('power', 'Power Consumption (W)', 'استهلاك الطاقة (واط)',
      'Under 50 W, 50-100 W, 101-150 W, 151-250 W, Above 250 W'),
    D('main', 'Model Year', 'سنة الإصدار', '2020, 2021, 2022, 2023, 2024, 2025, 2026'),
], COLOR, ELEC_COMMERCE)
